import { Router } from 'express';
import { z } from 'zod';
import { prisma } from '../prisma.js';
import { requireAuth } from '../middleware/auth.js';
import type { AuthRequest } from '../types.js';

export const tasksRouter = Router();
tasksRouter.use(requireAuth);
const statuses = ['OPEN','PLANNED','IN_PROGRESS','WAITING','DONE','ACCEPTED'] as const;
const priorities = ['LOW','NORMAL','HIGH','CRITICAL'] as const;
const payload = z.object({
  title: z.string().trim().min(2).max(160), description: z.string().trim().max(3000).optional().nullable(),
  status: z.enum(statuses).default('OPEN'), priority: z.enum(priorities).default('NORMAL'),
  assigneeId: z.string().uuid().optional().nullable(), plannedHours: z.coerce.number().min(0).max(9999).optional().nullable(),
  dueDate: z.coerce.date().optional().nullable(), checklist: z.array(z.object({ id: z.string().uuid().optional(), text: z.string().trim().min(1).max(250), done: z.boolean().default(false) })).max(50).default([]),
});
const include = { assignee: { select: { id:true, firstName:true, lastName:true } }, createdBy: { select: { id:true, firstName:true, lastName:true } }, checklist: { orderBy: { position:'asc' as const } }, comments: { include: { user: { select: { id:true, firstName:true, lastName:true } } }, orderBy: { createdAt:'asc' as const } }, timeEntries: { where: { status:'COMPLETED' as const }, select: { startTime:true, endTime:true, breaks:true } } };
function actualHours(task:any){ const mins=task.timeEntries.reduce((sum:number,e:any)=>{ const gross=e.endTime?Math.max(0,(e.endTime-e.startTime)/60000):0; const breaks=e.breaks.reduce((s:number,b:any)=>s+(b.endTime?Math.max(0,(b.endTime-b.startTime)/60000):0),0); return sum+Math.max(0,gross-breaks)},0); const {timeEntries,...rest}=task; return {...rest,actualHours:Math.round(mins)/60}; }
async function project(projectId:string, companyId:string){ return prisma.project.findFirst({where:{id:projectId,companyId}}); }
async function task(id:string, companyId:string){ return prisma.task.findFirst({where:{id,companyId},include}); }

tasksRouter.get('/users', async (req:AuthRequest,res)=>{ const users=await prisma.user.findMany({where:{companyId:req.auth!.companyId,active:true},select:{id:true,firstName:true,lastName:true,role:true},orderBy:[{firstName:'asc'},{lastName:'asc'}]}); res.json(users); });
tasksRouter.get('/projects/:projectId', async (req:AuthRequest,res)=>{ if(!await project(req.params.projectId,req.auth!.companyId)) return res.status(404).json({error:'Baustelle nicht gefunden.'}); const rows=await prisma.task.findMany({where:{projectId:req.params.projectId,companyId:req.auth!.companyId},include,orderBy:[{status:'asc'},{position:'asc'},{createdAt:'desc'}]}); res.json(rows.map(actualHours)); });
tasksRouter.post('/projects/:projectId', async (req:AuthRequest,res)=>{ const parsed=payload.safeParse(req.body); if(!parsed.success) return res.status(400).json({error:'Bitte Aufgabenangaben prüfen.'}); if(!await project(req.params.projectId,req.auth!.companyId)) return res.status(404).json({error:'Baustelle nicht gefunden.'}); const max=await prisma.task.aggregate({where:{projectId:req.params.projectId,status:parsed.data.status},_max:{position:true}}); const row=await prisma.task.create({data:{companyId:req.auth!.companyId,projectId:req.params.projectId,createdById:req.auth!.userId,title:parsed.data.title,description:parsed.data.description||null,status:parsed.data.status,priority:parsed.data.priority,assigneeId:parsed.data.assigneeId||null,plannedHours:parsed.data.plannedHours??null,dueDate:parsed.data.dueDate??null,position:(max._max.position??-1)+1,checklist:{create:parsed.data.checklist.map((x,i)=>({text:x.text,done:x.done,position:i}))}},include}); res.status(201).json(actualHours(row)); });
tasksRouter.put('/:id', async (req:AuthRequest,res)=>{ const parsed=payload.safeParse(req.body); if(!parsed.success) return res.status(400).json({error:'Bitte Aufgabenangaben prüfen.'}); const current=await task(req.params.id,req.auth!.companyId); if(!current) return res.status(404).json({error:'Aufgabe nicht gefunden.'}); const row=await prisma.$transaction(async tx=>{ await tx.taskChecklistItem.deleteMany({where:{taskId:current.id}}); return tx.task.update({where:{id:current.id},data:{title:parsed.data.title,description:parsed.data.description||null,status:parsed.data.status,priority:parsed.data.priority,assigneeId:parsed.data.assigneeId||null,plannedHours:parsed.data.plannedHours??null,dueDate:parsed.data.dueDate??null,completedAt:['DONE','ACCEPTED'].includes(parsed.data.status)?current.completedAt??new Date():null,checklist:{create:parsed.data.checklist.map((x,i)=>({text:x.text,done:x.done,position:i}))}},include}); }); res.json(actualHours(row)); });
tasksRouter.patch('/:id/status', async (req:AuthRequest,res)=>{ const parsed=z.object({status:z.enum(statuses),position:z.number().int().min(0).default(0)}).safeParse(req.body); if(!parsed.success) return res.status(400).json({error:'Status ungültig.'}); const current=await task(req.params.id,req.auth!.companyId); if(!current) return res.status(404).json({error:'Aufgabe nicht gefunden.'}); const row=await prisma.task.update({where:{id:current.id},data:{status:parsed.data.status,position:parsed.data.position,completedAt:['DONE','ACCEPTED'].includes(parsed.data.status)?current.completedAt??new Date():null},include}); res.json(actualHours(row)); });
tasksRouter.post('/:id/comments', async (req:AuthRequest,res)=>{ const parsed=z.object({comment:z.string().trim().min(1).max(2000)}).safeParse(req.body); if(!parsed.success) return res.status(400).json({error:'Kommentar darf nicht leer sein.'}); const current=await task(req.params.id,req.auth!.companyId); if(!current) return res.status(404).json({error:'Aufgabe nicht gefunden.'}); const comment=await prisma.taskComment.create({data:{taskId:current.id,userId:req.auth!.userId,comment:parsed.data.comment},include:{user:{select:{id:true,firstName:true,lastName:true}}}}); res.status(201).json(comment); });
tasksRouter.delete('/:id', async (req:AuthRequest,res)=>{ const current=await task(req.params.id,req.auth!.companyId); if(!current) return res.status(404).json({error:'Aufgabe nicht gefunden.'}); await prisma.task.delete({where:{id:current.id}}); res.status(204).send(); });
