'use client';
import Link from 'next/link';
import { useMemo, useState } from 'react';
import { useParams } from 'next/navigation';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { ArrowLeft, Boxes, LoaderCircle, PackagePlus, Plus, Search, Trash2, TriangleAlert } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { createMaterial, createMaterialBooking, deleteMaterialBooking, getMaterials, getProjectMaterialBookings } from '@/services/materials';
import type { MaterialBookingType, MaterialUnit } from '@/types/material';

const unitLabels:Record<MaterialUnit,string>={PIECE:'Stk.',METER:'m',SQUARE_METER:'m²',KILOGRAM:'kg',LITER:'l',PACKAGE:'Pkg.',ROLL:'Rolle',OTHER:'Einheit'};
const units=Object.keys(unitLabels) as MaterialUnit[];
function n(v:string|number|null|undefined){ return Number(v ?? 0); }
function money(v:string|number|null|undefined){ return new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(n(v)); }
function errorText(error:any){ return error?.response?.data?.error ?? 'Aktion konnte nicht ausgeführt werden.'; }

export default function MaterialPage(){
 const params=useParams<{id:string}>(); const projectId=Array.isArray(params.id)?params.id[0]:params.id; const qc=useQueryClient();
 const [search,setSearch]=useState(''); const [message,setMessage]=useState(''); const [showMaster,setShowMaster]=useState(false);
 const [materialForm,setMaterialForm]=useState({articleNumber:'',name:'',manufacturer:'',unit:'PIECE' as MaterialUnit,purchasePrice:'',salesPrice:'',stockQuantity:'0',minimumStock:'0'});
 const [booking,setBooking]=useState({materialId:'',type:'CONSUMPTION' as MaterialBookingType,quantity:'1',note:''});
 const materials=useQuery({queryKey:['materials'],queryFn:()=>getMaterials()});
 const bookings=useQuery({queryKey:['material-bookings',projectId],queryFn:()=>getProjectMaterialBookings(projectId),enabled:Boolean(projectId)});
 const createMaster=useMutation({mutationFn:()=>createMaterial({articleNumber:materialForm.articleNumber,name:materialForm.name,manufacturer:materialForm.manufacturer||null,unit:materialForm.unit,purchasePrice:materialForm.purchasePrice?Number(materialForm.purchasePrice):null,salesPrice:materialForm.salesPrice?Number(materialForm.salesPrice):null,stockQuantity:Number(materialForm.stockQuantity),minimumStock:Number(materialForm.minimumStock),active:true}),onSuccess:async(row)=>{setMessage('Material wurde angelegt.');setShowMaster(false);setMaterialForm({articleNumber:'',name:'',manufacturer:'',unit:'PIECE',purchasePrice:'',salesPrice:'',stockQuantity:'0',minimumStock:'0'});await qc.invalidateQueries({queryKey:['materials']});setBooking(b=>({...b,materialId:row.id}));},onError:e=>setMessage(errorText(e))});
 const createBooking=useMutation({mutationFn:()=>createMaterialBooking(projectId,{materialId:booking.materialId,type:booking.type,quantity:Number(booking.quantity),note:booking.note||null}),onSuccess:async()=>{setMessage('Materialbuchung wurde gespeichert.');setBooking(b=>({...b,quantity:'1',note:''}));await Promise.all([qc.invalidateQueries({queryKey:['materials']}),qc.invalidateQueries({queryKey:['material-bookings',projectId]})]);},onError:e=>setMessage(errorText(e))});
 const removeBooking=useMutation({mutationFn:deleteMaterialBooking,onSuccess:async()=>{setMessage('Buchung wurde storniert.');await Promise.all([qc.invalidateQueries({queryKey:['materials']}),qc.invalidateQueries({queryKey:['material-bookings',projectId]})]);},onError:e=>setMessage(errorText(e))});
 const filtered=useMemo(()=>materials.data?.filter(x=>`${x.articleNumber} ${x.name} ${x.manufacturer??''}`.toLowerCase().includes(search.toLowerCase()))??[],[materials.data,search]);
 const summary=useMemo(()=>{const rows=bookings.data??[];return {count:rows.length,value:rows.reduce((s,b)=>s+(b.type==='CONSUMPTION'?1:-1)*n(b.quantity)*n(b.unitPrice),0)}},[bookings.data]);
 return <div className="space-y-6">
  <div><Link href={`/projects/${projectId}`} className="mb-4 inline-flex items-center gap-2 text-sm text-slate-600 hover:text-slate-950"><ArrowLeft className="size-4"/>Zurück zur Baustelle</Link><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="text-3xl font-semibold tracking-tight">Material</h1><p className="mt-1 text-sm text-slate-500">Verbrauch buchen und Lagerbestand im Blick behalten.</p></div><Button onClick={()=>setShowMaster(v=>!v)}><Plus className="size-4"/>Neues Material</Button></div></div>
  {message?<div className="rounded-xl border bg-white px-4 py-3 text-sm">{message}</div>:null}
  <div className="grid gap-4 md:grid-cols-3"><Card><CardHeader className="pb-2"><CardTitle className="text-sm text-slate-500">Buchungen</CardTitle></CardHeader><CardContent><p className="text-2xl font-semibold">{summary.count}</p></CardContent></Card><Card><CardHeader className="pb-2"><CardTitle className="text-sm text-slate-500">Projektwert netto</CardTitle></CardHeader><CardContent><p className="text-2xl font-semibold">{money(summary.value)}</p></CardContent></Card><Card><CardHeader className="pb-2"><CardTitle className="text-sm text-slate-500">Mindestbestand erreicht</CardTitle></CardHeader><CardContent><p className="text-2xl font-semibold">{materials.data?.filter(x=>x.lowStock).length??0}</p></CardContent></Card></div>
  {showMaster?<Card><CardHeader><CardTitle>Materialstamm anlegen</CardTitle></CardHeader><CardContent><form className="grid gap-4 md:grid-cols-4" onSubmit={e=>{e.preventDefault();setMessage('');createMaster.mutate();}}><Input placeholder="Artikelnummer" required value={materialForm.articleNumber} onChange={e=>setMaterialForm(f=>({...f,articleNumber:e.target.value}))}/><Input placeholder="Bezeichnung" required value={materialForm.name} onChange={e=>setMaterialForm(f=>({...f,name:e.target.value}))}/><Input placeholder="Hersteller" value={materialForm.manufacturer} onChange={e=>setMaterialForm(f=>({...f,manufacturer:e.target.value}))}/><select className="h-9 rounded-md border px-3 text-sm" value={materialForm.unit} onChange={e=>setMaterialForm(f=>({...f,unit:e.target.value as MaterialUnit}))}>{units.map(u=><option key={u} value={u}>{unitLabels[u]}</option>)}</select><Input type="number" min="0" step="0.01" placeholder="EK netto" value={materialForm.purchasePrice} onChange={e=>setMaterialForm(f=>({...f,purchasePrice:e.target.value}))}/><Input type="number" min="0" step="0.01" placeholder="VK netto" value={materialForm.salesPrice} onChange={e=>setMaterialForm(f=>({...f,salesPrice:e.target.value}))}/><Input type="number" min="0" step="0.001" placeholder="Lagerbestand" value={materialForm.stockQuantity} onChange={e=>setMaterialForm(f=>({...f,stockQuantity:e.target.value}))}/><Input type="number" min="0" step="0.001" placeholder="Mindestbestand" value={materialForm.minimumStock} onChange={e=>setMaterialForm(f=>({...f,minimumStock:e.target.value}))}/><div className="md:col-span-4 flex justify-end"><Button type="submit" disabled={createMaster.isPending}>{createMaster.isPending?<LoaderCircle className="size-4 animate-spin"/>:<PackagePlus className="size-4"/>}Material speichern</Button></div></form></CardContent></Card>:null}
  <Card><CardHeader><CardTitle>Material auf Baustelle buchen</CardTitle></CardHeader><CardContent><form className="grid gap-4 md:grid-cols-[2fr_1fr_1fr_2fr_auto]" onSubmit={e=>{e.preventDefault();setMessage('');createBooking.mutate();}}><select required className="h-9 rounded-md border px-3 text-sm" value={booking.materialId} onChange={e=>setBooking(b=>({...b,materialId:e.target.value}))}><option value="">Material auswählen</option>{materials.data?.filter(x=>x.active).map(x=><option key={x.id} value={x.id}>{x.articleNumber} · {x.name} ({n(x.stockQuantity)} {unitLabels[x.unit]})</option>)}</select><select className="h-9 rounded-md border px-3 text-sm" value={booking.type} onChange={e=>setBooking(b=>({...b,type:e.target.value as MaterialBookingType}))}><option value="CONSUMPTION">Verbrauch</option><option value="RETURN">Rückgabe</option></select><Input required type="number" min="0.001" step="0.001" value={booking.quantity} onChange={e=>setBooking(b=>({...b,quantity:e.target.value}))}/><Input placeholder="Notiz / Einbauort" value={booking.note} onChange={e=>setBooking(b=>({...b,note:e.target.value}))}/><Button type="submit" disabled={createBooking.isPending||!booking.materialId}>{createBooking.isPending?<LoaderCircle className="size-4 animate-spin"/>:<Boxes className="size-4"/>}Buchen</Button></form></CardContent></Card>
  <div className="grid gap-6 xl:grid-cols-[1fr_1.2fr]"><Card><CardHeader><CardTitle>Materialstamm</CardTitle></CardHeader><CardContent><div className="relative mb-4"><Search className="absolute left-3 top-2.5 size-4 text-slate-400"/><Input className="pl-9" placeholder="Artikel suchen" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="max-h-[520px] space-y-2 overflow-auto">{materials.isLoading?<LoaderCircle className="size-5 animate-spin"/>:filtered.map(x=><div key={x.id} className="rounded-xl border p-3"><div className="flex items-start justify-between gap-3"><div><p className="font-medium">{x.name}</p><p className="text-xs text-slate-500">{x.articleNumber}{x.manufacturer?` · ${x.manufacturer}`:''}</p></div>{x.lowStock?<TriangleAlert className="size-5 text-amber-500"/>:null}</div><div className="mt-2 flex justify-between text-sm"><span>Bestand: <b>{n(x.stockQuantity)} {unitLabels[x.unit]}</b></span><span>{money(x.salesPrice??x.purchasePrice)}</span></div></div>)}</div></CardContent></Card>
  <Card><CardHeader><CardTitle>Baustellenbuchungen</CardTitle></CardHeader><CardContent><div className="space-y-2">{bookings.isLoading?<LoaderCircle className="size-5 animate-spin"/>:bookings.data?.length?bookings.data.map(b=><div key={b.id} className="flex items-center justify-between gap-4 rounded-xl border p-3"><div><p className="font-medium">{b.material.name}</p><p className="text-xs text-slate-500">{new Intl.DateTimeFormat('de-DE',{dateStyle:'medium',timeStyle:'short'}).format(new Date(b.bookedAt))} · {b.bookedBy.firstName} {b.bookedBy.lastName}</p>{b.note?<p className="mt-1 text-sm text-slate-600">{b.note}</p>:null}</div><div className="flex items-center gap-3"><div className="text-right"><p className={b.type==='CONSUMPTION'?'font-semibold text-red-700':'font-semibold text-emerald-700'}>{b.type==='CONSUMPTION'?'-':'+'}{n(b.quantity)} {unitLabels[b.material.unit]}</p><p className="text-xs text-slate-500">{money(n(b.quantity)*n(b.unitPrice))}</p></div><Button type="button" variant="ghost" size="icon" onClick={()=>removeBooking.mutate(b.id)} aria-label="Buchung stornieren"><Trash2 className="size-4"/></Button></div></div>):<p className="text-sm text-slate-500">Noch keine Materialbuchung vorhanden.</p>}</div></CardContent></Card></div>
 </div>
}
